server:
  port: 8081 # 端口

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wp123456

  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        logger-level: FULL
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 20000


# Seata 配置项，对应 SeataProperties 类
seata:
  enabled: true
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: my_test_tx_group # Seata 事务组编号，用于 TC 集群名
  enable-auto-data-source-proxy: true
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

